const PRESETS = {
  suave: {
    monochrome: 70,
    pixelSize: 2,
    noise: 12,
    lowContrast: 15,
    bloom: 25,
    bloomThreshold: 75,
    scanlines: 18,
    scanlineSpacing: 4,
    vignette: 35,
    distortion: 8,
    halftone: 12,
    dotSize: 5,
    intensity: 80,
  },
  intenso: {
    monochrome: 95,
    pixelSize: 6,
    noise: 38,
    lowContrast: 45,
    bloom: 65,
    bloomThreshold: 55,
    scanlines: 55,
    scanlineSpacing: 3,
    vignette: 70,
    distortion: 28,
    halftone: 40,
    dotSize: 7,
  },
  terminal: {
    monochrome: 100,
    pixelSize: 3,
    noise: 15,
    lowContrast: 20,
    bloom: 55,
    bloomThreshold: 60,
    scanlines: 40,
    scanlineSpacing: 3,
    vignette: 45,
    distortion: 5,
    halftone: 0,
    dotSize: 6,
  },
  pixel: {
    monochrome: 0,
    pixelSize: 8,
    noise: 0,
    lowContrast: 0,
    bloom: 50,
    bloomThreshold: 20,
    scanlines: 0,
    scanlineSpacing: 0,
    vignette: 0,
    distortion: 0,
    halftone: 0,
    dotSize: 0,
    intensity: 100,
  },
};

export default PRESETS;

export type PresetKey = keyof typeof PRESETS;
